tag @s remove picarrow.ehm.has_id

scoreboard players reset @s picarrow.ehm.id
tag @s remove picarrow.ehm.id_00_0
tag @s remove picarrow.ehm.id_00_1
tag @s remove picarrow.ehm.id_01_0
tag @s remove picarrow.ehm.id_01_1
tag @s remove picarrow.ehm.id_02_0
tag @s remove picarrow.ehm.id_02_1
tag @s remove picarrow.ehm.id_03_0
tag @s remove picarrow.ehm.id_03_1
tag @s remove picarrow.ehm.id_04_0
tag @s remove picarrow.ehm.id_04_1
tag @s remove picarrow.ehm.id_05_0
tag @s remove picarrow.ehm.id_05_1
tag @s remove picarrow.ehm.id_06_0
tag @s remove picarrow.ehm.id_06_1
tag @s remove picarrow.ehm.id_07_0
tag @s remove picarrow.ehm.id_07_1
tag @s remove picarrow.ehm.id_08_0
tag @s remove picarrow.ehm.id_08_1
tag @s remove picarrow.ehm.id_09_0
tag @s remove picarrow.ehm.id_09_1
tag @s remove picarrow.ehm.id_10_0
tag @s remove picarrow.ehm.id_10_1
tag @s remove picarrow.ehm.id_11_0
tag @s remove picarrow.ehm.id_11_1
tag @s remove picarrow.ehm.id_12_0
tag @s remove picarrow.ehm.id_12_1
tag @s remove picarrow.ehm.id_13_0
tag @s remove picarrow.ehm.id_13_1
tag @s remove picarrow.ehm.id_14_0
tag @s remove picarrow.ehm.id_14_1
tag @s remove picarrow.ehm.id_15_0
tag @s remove picarrow.ehm.id_15_1
tag @s remove picarrow.ehm.id_16_0
tag @s remove picarrow.ehm.id_16_1
tag @s remove picarrow.ehm.id_17_0
tag @s remove picarrow.ehm.id_17_1
tag @s remove picarrow.ehm.id_18_0
tag @s remove picarrow.ehm.id_18_1
tag @s remove picarrow.ehm.id_19_0
tag @s remove picarrow.ehm.id_19_1
tag @s remove picarrow.ehm.id_20_0
tag @s remove picarrow.ehm.id_20_1
tag @s remove picarrow.ehm.id_21_0
tag @s remove picarrow.ehm.id_21_1
tag @s remove picarrow.ehm.id_22_0
tag @s remove picarrow.ehm.id_22_1
tag @s remove picarrow.ehm.id_23_0
tag @s remove picarrow.ehm.id_23_1
tag @s remove picarrow.ehm.id_24_0
tag @s remove picarrow.ehm.id_24_1
tag @s remove picarrow.ehm.id_25_0
tag @s remove picarrow.ehm.id_25_1
tag @s remove picarrow.ehm.id_26_0
tag @s remove picarrow.ehm.id_26_1
tag @s remove picarrow.ehm.id_27_0
tag @s remove picarrow.ehm.id_27_1
tag @s remove picarrow.ehm.id_28_0
tag @s remove picarrow.ehm.id_28_1
tag @s remove picarrow.ehm.id_29_0
tag @s remove picarrow.ehm.id_29_1
tag @s remove picarrow.ehm.id_30_0
tag @s remove picarrow.ehm.id_30_1
tag @s remove picarrow.ehm.id_31_0
tag @s remove picarrow.ehm.id_31_1
