scoreboard players reset @s picarrow.ehm._

tag @s remove picarrow.ehm.00_0
tag @s remove picarrow.ehm.00_1
tag @s remove picarrow.ehm.01_0
tag @s remove picarrow.ehm.01_1
tag @s remove picarrow.ehm.02_0
tag @s remove picarrow.ehm.02_1
tag @s remove picarrow.ehm.03_0
tag @s remove picarrow.ehm.03_1
tag @s remove picarrow.ehm.04_0
tag @s remove picarrow.ehm.04_1
tag @s remove picarrow.ehm.05_0
tag @s remove picarrow.ehm.05_1
tag @s remove picarrow.ehm.06_0
tag @s remove picarrow.ehm.06_1
tag @s remove picarrow.ehm.07_0
tag @s remove picarrow.ehm.07_1
tag @s remove picarrow.ehm.08_0
tag @s remove picarrow.ehm.08_1
tag @s remove picarrow.ehm.09_0
tag @s remove picarrow.ehm.09_1
tag @s remove picarrow.ehm.10_0
tag @s remove picarrow.ehm.10_1
tag @s remove picarrow.ehm.11_0
tag @s remove picarrow.ehm.11_1
tag @s remove picarrow.ehm.12_0
tag @s remove picarrow.ehm.12_1
tag @s remove picarrow.ehm.13_0
tag @s remove picarrow.ehm.13_1
tag @s remove picarrow.ehm.14_0
tag @s remove picarrow.ehm.14_1
tag @s remove picarrow.ehm.15_0
tag @s remove picarrow.ehm.15_1
tag @s remove picarrow.ehm.16_0
tag @s remove picarrow.ehm.16_1
tag @s remove picarrow.ehm.17_0
tag @s remove picarrow.ehm.17_1
tag @s remove picarrow.ehm.18_0
tag @s remove picarrow.ehm.18_1
tag @s remove picarrow.ehm.19_0
tag @s remove picarrow.ehm.19_1
tag @s remove picarrow.ehm.20_0
tag @s remove picarrow.ehm.20_1
tag @s remove picarrow.ehm.21_0
tag @s remove picarrow.ehm.21_1
tag @s remove picarrow.ehm.22_0
tag @s remove picarrow.ehm.22_1
tag @s remove picarrow.ehm.23_0
tag @s remove picarrow.ehm.23_1
tag @s remove picarrow.ehm.24_0
tag @s remove picarrow.ehm.24_1
tag @s remove picarrow.ehm.25_0
tag @s remove picarrow.ehm.25_1
tag @s remove picarrow.ehm.26_0
tag @s remove picarrow.ehm.26_1
tag @s remove picarrow.ehm.27_0
tag @s remove picarrow.ehm.27_1
tag @s remove picarrow.ehm.28_0
tag @s remove picarrow.ehm.28_1
tag @s remove picarrow.ehm.29_0
tag @s remove picarrow.ehm.29_1
tag @s remove picarrow.ehm.30_0
tag @s remove picarrow.ehm.30_1
tag @s remove picarrow.ehm.31_0
tag @s remove picarrow.ehm.31_1
